name: Publish

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip

      - name: Install build tool
        run: pip install gradio

      - name: Install ${{ vars.PACKAGE_NAME }}
        run: gradio cc install

      - name: Build ${{ vars.PACKAGE_NAME }}
        run: gradio cc build

      - name: Upload ${{ vars.PACKAGE_NAME }} package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.PACKAGE_NAME }}
          path: ./dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: PyPI
      url: https://pypi.org/project/${{ vars.PACKAGE_NAME }}/
    steps:
      - name: Download ${{ vars.PACKAGE_NAME }} wheels
        uses: actions/download-artifact@v4
        with:
          name: ${{ vars.PACKAGE_NAME }}
          path: ./dist/

      - name: Publish ${{ vars.PACKAGE_NAME }}
        uses: pypa/gh-action-pypi-publish@release/v1
